### ISSUE TITLE
On-Tracker. API prototype. Create a basic structure

### ISSUE THREAD

**Issue by live-dev999** [LiveDevTeam/O2NextGen#113]
Step 1:

- [ ]  Create a empty project mvc (.net core 2.2)
- [ ]   Implement basic configuration
- [ ]   Implement basic middleware
